sudo: false
language: erlang
otp_release:
  - "18.2.1"
cache:
  directories:
  - $HOME/otp/18.2.1
  - $HOME/.cache/rebar3
  - _plt
install: "true"
script: "make testclean dist coveralls"
branches:
  only:
    - master
    - develop
notifications:
  email:
    - priestjim@gmail.com

