sudo: false
language: erlang
otp_release:
  - 18.2.4
  - 17.5.6.8
cache:
  directories:
  - $HOME/otp/18.2.4
  - $HOME/otp/17.5.6.8
  - $HOME/.cache/rebar3
  - _plt
install: "true"
script: "make testclean dist coveralls"
branches:
  only:
    - master
    - develop

notifications:
  email:
    - priestjim@gmail.com

