sudo: false
language: erlang
otp_release:
  - 18.2
  - 18.1
  - 18.0
  - 17.5
cache:
  directories:
  - $HOME/.cache/rebar3
  - _plt
install: "true"
script: "make testclean dist"
after-sucess: "make coveralls"
branches:
  only:
    - master
    - develop

notifications:
  email:
    - priestjim@gmail.com

